=== MobilityData/gbfs-json-schema/v3.0/gbfs.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/MobilityData/gbfs/blob/v3.0/gbfs.md#gbfsjson",
  "description": "Auto-discovery file that links to all of the other files published by the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.0"
    },
    "data": {
      "type": "object",
      "properties": {
        "feeds": {
          "description": "An array of all of the feeds that are published by the auto-discovery file. Each element in the array is an object with the keys below.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "description": "Key identifying the type of feed this is. The key must be the base file name defined in the spec for the corresponding feed type.",
                "type": "string",
                "enum": [
                  "gbfs",
                  "gbfs_versions",
                  "system_information",
                  "vehicle_types",
                  "station_information",
                  "station_status",
                  "vehicle_status",
                  "system_alerts",
                  "system_regions",
                  "system_pricing_plans",
                  "geofencing_zones"
                ]
              },
              "url": {
                "description": "URL for the feed.",
                "type": "string",
                "format": "uri"
              }
            },
            "required": ["name", "url"]
          },
          "minItems": 1,
          "contains": {
            "properties": {
              "name": { "const": "system_information" }
            }
          },
          "allOf": [
            {
              "anyOf": [
                {
                  "contains": {
                    "properties": {
                      "name": { "const": "station_status" }
                    }
                  }
                },
                {
                  "contains": {
                    "properties": {
                      "name": { "const": "vehicle_status" }
                    }
                  }
                }
              ]
            },
            {
              "if": {
                "contains": {
                  "properties": {
                    "name": { "const": "station_information" }
                  }
                }
              },
              "then": {
                "contains": {
                  "properties": {
                    "name": { "const": "station_status" }
                  }
                }
              }
            }
          ]
        }
      },
      "required": ["feeds"]
    }
  },
  "additionalProperties": false,
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.0/gbfs.json
{
    "last_updated": "2019-07-04T13:33:03.969Z",
    "ttl": 60,
    "version": "3.0",
    "data": {
        "feeds": [
            {
                "name": "system_information",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/system-information"
            },
            {
                "name": "vehicle_status",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/vehicle-status"
            },
            {
                "name": "vehicle_types",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/vehicle-types"
            },
            {
                "name": "system_pricing_plans",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/system-pricing-plans"
            },
            {
                "name": "station_information",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/station-information"
            },
            {
                "name": "station_status",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/station-status"
            },
            {
                "name": "geofencing_zones",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/geofencing-zones"
            },
            {
                "name": "gbfs_versions",
                "url": "https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/versions"
            }
        ]
    }
}

=== MobilityData/gbfs-json-schema/models/rust/src/3.0/files/examples/specification/gbfs.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 0,
    "version": "3.0",
    "data": {
        "feeds": [
            {
                "name": "system_information",
                "url": "https://www.example.com/gbfs/1/system_information"
            },
            {
                "name": "station_information",
                "url": "https://www.example.com/gbfs/1/station_information"
            }
        ]
    }
}
